language: ruby
notifications:
  email: false
cache:
  - bundler
  - yarn
services:
  - postgresql
before_install:
  - nvm install --lts
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - bundle install --jobs=3 --retry=3
  - yarn
  - bundle exec rake db:setup
script:
  - bundle exec rspec

