development:
  mail:
    password: 
    user_name: 

test:
  mail:
    password: password
    user_name: test

aws:
  S3_REGION: eu-north-1
  S3_ACCESS_KEY: 
  S3_SECRET_KEY: 
  S3_BUCKET_NAME: bbq-robb

yandex_api_key:

# Used as the base secret for all MessageVerifiers in Rails, including the one protecting cookies.
secret_key_base:
