# aws:
#   access_key_id: 123
#   secret_access_key: 345

development:
  mail:
    password: 
    user_name: 

test:
  mail:
    password: password
    user_name: test

yandex_api_key:

# Used as the base secret for all MessageVerifiers in Rails, including the one protecting cookies.
secret_key_base:
